-- MySQL Script generated by MySQL Workbench
-- Sun Jan 17 13:49:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FrFrFrFr
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FrFrFrFr
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FrFrFrFr` DEFAULT CHARACTER SET utf8mb4 ;
USE `FrFrFrFr` ;

-- -----------------------------------------------------
-- Table `FrFrFrFr`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FrFrFrFr`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `zip` VARCHAR(5) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `street` VARCHAR(70) NOT NULL,
  `number` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `FrFrFrFr`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FrFrFrFr`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `email` VARCHAR(120) NOT NULL,
  `passwordHash` VARCHAR(255) NOT NULL,
  `firstName` VARCHAR(50) NOT NULL,
  `lastName` VARCHAR(50) NOT NULL,
  `address_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_user_address_idx` (`address_id` ASC),
  CONSTRAINT `fk_user_address`
    FOREIGN KEY (`address_id`)
    REFERENCES `FrFrFrFr`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `FrFrFrFr`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FrFrFrFr`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `FrFrFrFr`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `FrFrFrFr`.`shoppingCart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FrFrFrFr`.`shoppingCart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_shoppingCart_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_shoppingCart_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `FrFrFrFr`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `FrFrFrFr`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FrFrFrFr`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `FrFrFrFr`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FrFrFrFr`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `name` VARCHAR(50) NOT NULL,
  `price` DECIMAL(4,2) NOT NULL,
  `numberInStock` INT NOT NULL,
  `description` VARCHAR(300) NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `FrFrFrFr`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `FrFrFrFr`.`productInShoppingCart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FrFrFrFr`.`productInShoppingCart` (
  `shoppingCart_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`shoppingCart_id`, `product_id`),
  INDEX `fk_productInShoppingCart_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_productInShoppingCart_shoppingCart1`
    FOREIGN KEY (`shoppingCart_id`)
    REFERENCES `FrFrFrFr`.`shoppingCart` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productInShoppingCart_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `FrFrFrFr`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FrFrFrFr`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FrFrFrFr`.`image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `imageUrl` VARCHAR(255) NOT NULL,
  `altText` VARCHAR(100) NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_image_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_image_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `FrFrFrFr`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
